[package]
name = "stellar-dominion"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = []

[dependencies]
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "stellar-dominion"
path = "src/main.rs"